### ISSUE TITLE
not available on mac m1

### ISSUE THREAD

**Issue by FingerLiu** [MLT-OSS/open-assistant-api#33]
docker compose up failed:
```
no matching manifest for linux/arm64/v8 in the manifest list entries
```

maybe you did not build api/worker on mac?

**Comment by kense-lab** [comment]
![image](https://github.com/Tuanzi1015/open-assistant-api/assets/37998568/45489d9c-ef62-4ef4-8333-2de6afefe308)
Is it a problem here? Let go of these code comments and give it a try
