### ISSUE TITLE
一直打印 in progress...

### ISSUE THREAD

**Issue by gaohan-cmd** [MLT-OSS/open-assistant-api#49]
您好，请问我这边配置好密钥后，启动docker后运行python tests/e2e/index.py一直打印in progress，而不输出结果是正常的嘛
![image](https://github.com/MLT-OSS/open-assistant-api/assets/63499259/2c29f710-e722-4e14-9d06-00fd25c9be0a)
![image](https://github.com/MLT-OSS/open-assistant-api/assets/63499259/c67185e7-f654-4075-b56a-368d9120773a)

**Comment by liuooo** [comment]
提供一下 api / worker 的 log 信息进行排查。

**Comment by gaohan-cmd** [comment]
> 提供一下 api / worker 的 log 信息进行排查。

抱歉，该项目运行环境我已经移除了，所以暂时找不到log信息了，但我看#50的问题是和我一样的，他已经贴了log
