### ISSUE TITLE
InternalServerError When Submitting Tool Outputs Due to Coroutine Handling Error

### ISSUE THREAD

**Issue by VRSEN** [MLT-OSS/open-assistant-api#61]
### Description
While running an assistant integrated with a custom tool, attempting to submit tool outputs using the provided method results in an internal server error. The issue arises when trying to execute the following line of code:
```python
client.beta.threads.runs.submit_tool_outputs(
    thread_id=self.thread.id,
    run_id=self.run.id,
    tool_outputs=tool_outputs
)
```

### Steps to Reproduce
1. Create an assistant with any basic custom tool.
2. Run the assistant and trigger the use of this tool.
3. Attempt to submit tool outputs using the method mentioned.
4. Observe the resulting error.

### Expected Behaviour
The system should handle the submission of tool outputs seamlessly, allowing the conversation with the assistant to continue without interruption.

### Actual Behaviour
Instead of the expected seamless conversation continuation, the system responds with an internal server error. The specific error message received from the API response is:
```
openai.InternalServerError: Error code: 500 - {'error': {'code': 'internal_server_error', 'message': 'Internal Server Error', 'type': None, 'param': None}}
```
This error is linked to an AttributeError on the backend, specifically with coroutine object handling in asynchronous database operations:
```
AttributeError: 'coroutine' object has no attribute 'scalars'
```

### Additional Information
- OpenAI Client Version: 1.14.2
- Python Version: 3.10.13
- Operating System: macOS 14.1.1 (23B81)
- Deployment: Running the latest code from the main branch using Docker Compose.

A fix for this issue involving the proper handling of asynchronous operations in SQLAlchemy is currently being prepared and will be submitted shortly.

**Comment by liuooo** [comment]
Thanks for your contribution!
